### ISSUE TITLE
storing url

### ISSUE THREAD

**Issue by hvorragend** [zikula-modules/EZComments#16]
I think that EZComments should not store the current URL with each comment.

We should store:

```
module
type
func
parameter 
```

Because:
If we use DirectoryBased? ShortURLs and we change the title of e.g. news or publication, the EZComments-URL to this comment (block) isn't correct anymore.

---

I like the way crpTag does it: call *_userapi_getmodulemeta to get the information

**Comment by paustian** [comment]
Urls work in v4.0.0
