### ISSUE TITLE
Show main content even without permission for comments

### ISSUE THREAD

**Issue by rmaiwald** [zikula-modules/EZComments#23]
When EZComments 2.0.0 is hooked to another module and a user has permission to view the module contents but has no persionn to view the comments too, the whole page will not be displayed. Instead the request is redirected to the login screen.

The function EZComments_user_view in pnuser.php (EZComments 2.0.0) always returns with LogUtil::registerPermissionError(), when checkPermission() fails. Other hook modules return empty content, if called as a hook.

EZComments should do so too, i.e. check if the GUI function was called as a hook ($objectid != '') and the return empty content (return false) rather than call LogUtil::registerPermissionError().

Regards
Reiner

**Comment by paustian** [comment]
Not an issue with v4.0.0. Comment permissions can be set using the permission system.
