### ISSUE TITLE
Scribite icons mis-aligned

### ISSUE THREAD

**Issue by robbrandt** [zikula-modules/EZComments#30]
I think this is an EZ Comments issue because the issue doesn't show up in EZ Comments when it is attached to other modules I've used.

When Scribite is enabled for the comments, the icons are shifted lower than the actual button areas, by about the size of the button areas themselves.  I have tried this with my own theme as well as the unaltered Andreas08 theme as well as seabreeze.

**Comment by Guite** [comment]
Closing in favour of #53
