### ISSUE TITLE
[EZComments v3.0.0] upgrade error

### ISSUE THREAD

**Issue by ghost** [zikula-modules/EZComments#41]
Upgrade from v2.0.0 fails, base system is zk135

Result:
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ksvw.ezcomments' doesn't exist. Failing Query: "DESCRIBE ezcomments"

Trace:
#0 Ausnahmefehler in C:\Daten\Homepages\webserver\UniServer\www\zk\lib\vendor\Doctrine\Doctrine\Connection.php, Zeile 1082
#1 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\vendor\Doctrine\Doctrine\Connection.php(862): Doctrine_Connection->execute('DESCRIBE ezcomm...', Array)
#2 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\vendor\Doctrine\Doctrine\Import\Mysql.php(143): Doctrine_Connection->fetchAssoc('DESCRIBE ezcomm...')
#3 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\util\DBUtil.php(3526): Doctrine_Import_Mysql->listTableColumns('ezcomments')
#4 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\util\DBUtil.php(3189): DBUtil::metaColumnNames('EZComments')
#5 C:\Daten\Homepages\webserver\UniServer\www\zk\modules\EZComments\lib\EZComments\Installer.php(81): DBUtil::changeTable('EZComments')
#6 [internal function]: EZComments_Installer->upgrade('2.0.0')
#7 C:\Daten\Homepages\webserver\UniServer\www\zk\system\Extensions\lib\Extensions\Api\Admin.php(1024): call_user_func(Array, '2.0.0')
#8 [internal function]: Extensions_Api_Admin->upgrade(Array)
#9 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\util\ModUtil.php(1091): call_user_func(Array, Array)
#10 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\util\ModUtil.php(1199): ModUtil::exec('Extensions', 'admin', 'upgrade', Array, true, NULL)
#11 C:\Daten\Homepages\webserver\UniServer\www\zk\system\Extensions\lib\Extensions\Controller\Admin.php(721): ModUtil::apiFunc('Extensions', 'admin', 'upgrade', Array)
#12 [internal function]: Extensions_Controller_Admin->upgrade(Array)
#13 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\util\ModUtil.php(1091): call_user_func(Array, Array)
#14 C:\Daten\Homepages\webserver\UniServer\www\zk\lib\util\ModUtil.php(1173): ModUtil::exec('Extensions', 'admin', 'upgrade', Array, false, NULL)
#15 C:\Daten\Homepages\webserver\UniServer\www\zk\index.php(78): ModUtil::func('Extensions', 'admin', 'upgrade', Array)
#16 {main}

**Comment by paustian** [comment]
As far as I know, this is resolved.
