### ISSUE TITLE
Comments for guests

### ISSUE THREAD

**Issue by AlexL777** [zikula-modules/EZComments#52]
Hello Developers,

I can not figure out how anonymous guests can comment. In the options of this module I do not find this setting. I use ezComments in the news publisher.

Now I have created new permissions so that "Unregistered" users have a CommentsAccess. Unfortunately this does not affect comments and only logged in users are allowed to comment on me.

How can I fix this?

Thanks in advance.

**Comment by Portugao** [comment]
Are you sure, that your permissions are in the correct order?

**Comment by AlexL777** [comment]
Hello @Portugao ,
On the permissions I have also changed something, but there was equal errors in the front end. You can not add an authorization for all groups and allow "CommentAccess". Unfortunately that does not work.

This authorization has Zikula as the default.

I do not know what it can be. Unfortunately there are no options in the ezComments settings to allow comments for anonymous guests.

**Comment by Portugao** [comment]
Which version of EZComments?

**Comment by AlexL777** [comment]
Version 3.0.1!

**Comment by Portugao** [comment]
Sorry...I'm not able to use News under Zikula 1.4.5 and to have a look. Do you use 1.4.6?

**Comment by AlexL777** [comment]
No problem! Yes, I use Zikula 1.4.6, the last version. Can I work with Disqus at Zikula? Would that be possible?

**Comment by Portugao** [comment]
Checked this with Zikula 1.4.6, News 3.1.1 and EZComments 3.0.1 and it works for me.

Questions about Dizkus you should make on the support sites....

**Comment by AlexL777** [comment]
Thank you for your test @portugao

But I have decided for disqus comments and have already implemented them. This works fine for me :smile:

**Comment by paustian** [comment]
This is implemented in v4.0.0. I will double-check before I close it.

**Comment by paustian** [comment]
This is implemented in v4.0.0
