### ISSUE TITLE
Error in the method name

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/EZComments#56]
It's not possible access to the stats: /comments/admin/modulestats
Error log:
`Uncaught PHP Exception BadMethodCallException: "Undefined method 'mostActivePoster'. The method name must start with either findBy or findOneBy!"`

Caller controller https://github.com/zikula-modules/EZComments/blob/b6525dcffb6ee38c18751627a8a24cbfd298a77e/Controller/AdminController.php#L239

Repository https://github.com/zikula-modules/EZComments/blob/b6525dcffb6ee38c18751627a8a24cbfd298a77e/Entity/Repository/EZCommentsEntityRepository.php#L167

How you could see, the repository contain "s" at end that the controller haven't.
You must change the name in controller or repository in order to match.

**Comment by paustian** [comment]
Thanks for the detailed report. Fixed.
