### ISSUE TITLE
Subject is mandatory now

### ISSUE THREAD

**Issue by KratorD** [zikula-modules/EZComments#57]
Hello.

When you add a comment and you dont fill the subject field, an error message appear: `There was a problem with your comment?. Please enter a subject for your comment`
This field was not mandatory in the past. IMO this field should be optional, because this is not a mail or message that someone can receive without knowing the reason. 
You are already writing about an item, the subject is the item itself (I hope the reason is understood).

Also, when you reply a comment with a subject, i was waiting that the subject was auto-filled with `RE: (text from first subject)`, but when you reply, the field subject is empty, so that you have that write a new subject.

Thanks.

**Comment by paustian** [comment]
I have fixed this. You can now enter comments without a subject. I have also implemented replies to root(parent) comments to take the subject of the parent comments and add _Re: text of subject_ to the subject line,

You cannot reply to child comments, only to parents, but they do follow in order.
